# prek configuration for bunny-cdn-sdk
# https://prek.j178.dev/

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v4.5.0"
hooks = [
  { id = "check-json" },
  { id = "check-toml" },
  { id = "check-vcs-permalinks" },
  { id = "check-yaml" },
  { id = "check-xml" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-symlinks" },
  { id = "destroyed-symlinks" },
  { id = "check-merge-conflict" },
  { id = "detect-private-key" },
  { id = "no-commit-to-branch", args = ["--branch", "main"] }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.9.1"
hooks = [
  { id = "ruff", args = ["--fix"] },
  { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/python-jsonschema/check-jsonschema"
rev = "0.30.0"
hooks = [
  { id = "check-dependabot" },
  { id = "check-github-workflows" }
]
