[tox]
env_list = py312,py313,py314,lint,typecheck

[testenv]
runner = uv-venv-lock-runner
extras = cli
dependency_groups = test
commands = pytest --no-cov -q --tb=short {posargs}

[testenv:typecheck]
runner = uv-venv-lock-runner
extras = cli
dependency_groups = lint
commands = ty check src/

[testenv:lint]
runner = uv-venv-lock-runner
extras =
dependency_groups = lint
commands =
    ruff format --check .
    ruff check .
